### PR TITLE
Add more test image types

### PR DESCRIPTION
**Pull request by rsrock**
Also include a way to handle .zip image files

### CODE REVIEW

**Comment by timholy** [comment]
Failure is in ZipFile. Thanks for adding these!

**Comment by rsrock** [comment]
No problem.  I'm using them to expand the coverage of `QuartzImageIO`.  There may be one more coming at some point.

**Comment by rsrock** [comment]
While I have you, can you give me push access to AndorSIF?  I should take another stab at getting a small test file set up for that, especially now that it's out there as a registered package.

**Comment by rsrock** [comment]
Nevermind-- I think I have it already (missed the big green button, somehow...)

**Pull request merged**
